---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: .github
platforms:
  - name: "${image}-${tag}"
    image: "nbjwl/molecule:${image}.${tag}"
    pre_build_image: true
    override_command: False
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - "${image}"
    privileged: true
    env:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
      mirror: "${mirror}"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        docker_install_mirror: "${channel}"
        docker_repo_file: ''
        docker_download_url: ''
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
  