---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-docker
      environment:
        http_proxy: "{{ lookup('env','http_proxy') }}"
        https_proxy: "{{ lookup('env','https_proxy') }}"
        no_proxy: "{{ lookup('env','no_proxy') }}"
